import makeStyles from "@material-ui/core/styles/makeStyles";

export const useApplicationListComponentsStyles = makeStyles((theme) => ({
    modalBlock: {
        height: 'calc(100vh - 65px)',
        width: 'calc(100vw - 677px)',
        position: 'fixed',
        top: 65,
        right: 0,
        border: '1px solid rgb(117,117,117, .5)'
    },
    modalBlockHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#1A4879',
        height: 60,
        width: '100%',
        color: '#FFFFFF',
    },
    modalBlockHeaderTitle: {
        paddingLeft: 35,
        fontSize: 18,
        fontWeight: 600,
    },
    modalBlockHeaderTitleName: {
        display: 'box',
        lineClamp: 2,
        overflow: 'hidden',
        boxOrient: 'vertical',
        position: 'absolute',
        top: 12,
        left: 130,
        maxWidth: 510,
        flexBasis: 510,
        height: 35,
        paddingLeft: 25,
        fontSize: 14,
    },
    modalBlockContent: {
        height: 'calc(100vh - 60px)',
        backgroundColor: '#EBF3F6',
    },
    createApplicationForm: {
        paddingTop: 60,
        paddingLeft: 40,
        color: '#9A9A9A',
    },
    createApplicationFormName: {
        resize: 'none',
        marginTop: 16,
        marginRight: 85,
        marginBottom: 25,
        padding: 10,
        height: 65,
        maxWidth: 630,
        width: '42vw',
        borderRadius: 5,
        borderColor: '#B5BBBF',
        outline: 'none',
    },
    createApplicationFormDescription: {
        resize: 'none',
        marginTop: 16,
        marginRight: 85,
        marginBottom: 75,
        padding: 10,
        height: 110,
        width: '42vw',
        maxWidth: 630,
        borderRadius: 5,
        borderColor: '#B5BBBF',
        outline: 'none',
    },
}))